# Generated by Django 4.2.16 on 2024-12-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_order_buyer_remark_alter_order_created_at_and_more'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_set', to='trade.order', verbose_name='订单'),
        ),
    ]
