# Generated by Django 4.2.16 on 2024-12-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_spu_poc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='provider_code',
        ),
        migrations.AddField(
            model_name='sku',
            name='suppliers_list',
            field=models.JSONField(default=list, help_text='包含供应商信息：供应商代码、供应商货品编码、协商采购价、上次采购价、最低采购价、是否默认供应商', verbose_name='供应商列表'),
        ),
    ]
