# Generated by Django 4.2.16 on 2024-12-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_sku_provider_code_sku_suppliers_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='other_dimensions',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='其他尺寸'),
        ),
    ]
