# Generated by Django 4.2.16 on 2024-12-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_sku_other_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='spu',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='产品类型'),
        ),
    ]
