# Generated by Django 4.2.16 on 2024-12-27 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0005_spu_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品牌名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='品牌描述')),
                ('logo', models.CharField(blank=True, max_length=255, null=True, verbose_name='品牌Logo')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌列表',
                'db_table': 'gallery_brand',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['-created_at'], 'verbose_name': 'SKU', 'verbose_name_plural': 'SKU列表'},
        ),
        migrations.RemoveIndex(
            model_name='sku',
            name='gallery_sku_sku_cod_78e1d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='sku',
            name='gallery_sku_spu_id_d5bb39_idx',
        ),
        migrations.RemoveIndex(
            model_name='sku',
            name='gallery_sku_created_d8b747_idx',
        ),
        migrations.RemoveIndex(
            model_name='spu',
            name='gallery_spu_spu_cod_a8d7b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='spu',
            name='gallery_spu_categor_15b940_idx',
        ),
        migrations.RemoveIndex(
            model_name='spu',
            name='gallery_spu_sales_c_8a819a_idx',
        ),
        migrations.RemoveField(
            model_name='spu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='spu',
            name='spu_remark',
        ),
        migrations.AddField(
            model_name='sku',
            name='surface_treatment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='表面处理'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='color',
            field=models.CharField(max_length=50, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='高(mm)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='长(mm)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='material',
            field=models.CharField(max_length=50, verbose_name='材质'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='plating_process',
            field=models.CharField(choices=[('none', '无电镀'), ('gold', '镀金'), ('silver', '镀银'), ('nickel', '镀镍'), ('chrome', '镀铬'), ('copper', '镀铜'), ('other', '其他')], max_length=20, verbose_name='电镀工艺'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='SKU编码'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_name',
            field=models.CharField(max_length=100, verbose_name='SKU名称'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='spu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.spu', verbose_name='所属SPU'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='suppliers_list',
            field=models.JSONField(default=list, verbose_name='供应商列表'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='重量(g)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='宽(mm)'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='poc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='专员'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='product_type',
            field=models.CharField(choices=[('math_design', '设计款'), ('ready_made', '现货款'), ('raw_material', '材料'), ('packing_material', '包材')], max_length=20, verbose_name='产品类型'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='sales_channel',
            field=models.IntegerField(blank=True, choices=[(1, '线上'), (2, '线下'), (3, '全渠道')], null=True, verbose_name='销售渠道'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='spu_name',
            field=models.CharField(max_length=100, verbose_name='SPU名称'),
        ),
    ]
