# Generated by Django 4.2.16 on 2024-12-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_package_order'),
        ('trade', '0002_alter_order_buyer_remark_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_order', to='logistics.package', verbose_name='包裹'),
        ),
    ]
